export interface FactoryAgent {
  id: `A${number}`;
  name: string;
  domain: string;
  capabilities: string[];
  permissions: string[];
  approvalRequired: boolean;
}

export const AGENT_CAPABILITIES: Record<string, string[]> = {
  A00:["intent_analysis","creative_direction"], A01:["reference_analysis","identity_continuity"],
  A02:["game_direction","scope"], A03:["game_design","mechanics"], A04:["narrative_direction","branching_story"],
  A05:["story_architecture","story_bible"], A06:["character_design","character_specs"],
  A07:["world_design","world_rules"], A08:["level_design","encounter_layout"],
  A09:["quest_design","objectives"], A10:["dialogue","conversation_logic"], A11:["cinematic_direction","sequencing"],
  A12:["camera","shot_design"], A13:["gameplay_design","systems_interaction"], A14:["systems_design","progression"],
  A15:["economy","balancing"], A16:["ux_ui","interface_design"], A17:["technical_direction","architecture"],
  A18:["engine_integration","engine_adapter"], A19:["code_architecture","interfaces"],
  A20:["code_generation","refactoring"], A21:["ai_ml","inference"], A22:["asset_direction","asset_specs"],
  A23:["2d_art","sprites","ui_assets"], A24:["3d_art","models"], A25:["materials","textures"],
  A26:["animation"], A27:["rigging","skinning"], A28:["vfx","particles"],
  A29:["audio_direction","audio_pipeline"], A30:["music","adaptive_music"], A31:["sfx"],
  A32:["voice","dubbing"], A33:["localization","i18n"], A34:["optimization"],
  A35:["qa","test_plans"], A36:["playtest","telemetry_feedback"], A37:["security","threat_model"],
  A38:["ip","license_compliance"], A39:["build","packaging"], A40:["release","release_gates"],
  A41:["github","version_control"], A42:["cloud","workspace"], A43:["documentation"],
  A44:["continuity","canon_validation"], A45:["narrative_qa"], A46:["game_balance"],
  A47:["mobile_optimization"], A48:["performance","profiling"], A49:["provider_routing"],
  A50:["model_registry","model_selection"], A51:["game_knowledge","reference_retrieval"],
  A52:["research","evidence"], A53:["ideation","concept_variants"], A54:["gdd_compilation"],
  A55:["game_compilation","project_generation"], A56:["world_simulation"],
  A57:["npc_intelligence","behavior"], A58:["multiplayer","networking"],
  A59:["monetization_systems"], A60:["store_publishing"], A61:["telemetry","analytics"]
};

export const AGENT_PERMISSIONS: Record<string, string[]> = {
  A00:["read_project"], A01:["read_project","write_assets"], A02:["read_project","write_code"],
  A03:["read_project","write_code"], A04:["read_project","write_code"], A05:["read_project"],
  A06:["read_project","write_assets"], A07:["read_project","write_code"], A08:["read_project","write_code"],
  A09:["read_project","write_code"], A10:["read_project","write_code"], A11:["read_project","write_assets"],
  A12:["read_project","write_code"], A13:["read_project","write_code"], A14:["read_project","write_code"],
  A15:["read_project","write_code"], A16:["read_project","write_assets"], A17:["read_project","write_code"],
  A18:["read_project","write_code"], A19:["read_project","write_code"], A20:["read_project","write_code"],
  A21:["read_project","external_api"], A22:["read_project","write_assets"], A23:["read_project","write_assets"],
  A24:["read_project","write_assets"], A25:["read_project","write_assets"], A26:["read_project","write_assets"],
  A27:["read_project","write_assets"], A28:["read_project","write_assets"], A29:["read_project","write_assets"],
  A30:["read_project","write_assets"], A31:["read_project","write_assets"], A32:["read_project","external_api"],
  A33:["read_project","write_assets"], A34:["read_project","write_code"], A35:["read_project","run_tests"],
  A36:["read_project","run_tests"], A37:["read_project","run_tests"], A38:["read_project"],
  A39:["read_project","run_build"], A40:["read_project","publish"], A41:["read_project","write_code"],
  A42:["read_project","external_api"], A43:["read_project","write_code"], A44:["read_project"],
  A45:["read_project","run_tests"], A46:["read_project","write_code"], A47:["read_project","write_code"],
  A48:["read_project","run_tests"], A49:["read_project","external_api"], A50:["read_project"],
  A51:["read_project"], A52:["read_project","external_api"], A53:["read_project"],
  A54:["read_project","write_code"], A55:["read_project","write_code"], A56:["read_project","write_code"],
  A57:["read_project","write_code"], A58:["read_project","write_code"], A59:["read_project","write_code"],
  A60:["read_project","publish"], A61:["read_project","external_api"]
};

export const AGENT_REGISTRY: FactoryAgent[] = [
  { id: "A00", name: "Intent & Creative Director", domain: "design", capabilities: AGENT_CAPABILITIES["A00"] ?? [], permissions: AGENT_PERMISSIONS["A00"] ?? [], approvalRequired: false },
  { id: "A01", name: "Reference & Identity Analyst", domain: "design", capabilities: AGENT_CAPABILITIES["A01"] ?? [], permissions: AGENT_PERMISSIONS["A01"] ?? [], approvalRequired: false },
  { id: "A02", name: "Game Director", domain: "design", capabilities: AGENT_CAPABILITIES["A02"] ?? [], permissions: AGENT_PERMISSIONS["A02"] ?? [], approvalRequired: false },
  { id: "A03", name: "Game Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A03"] ?? [], permissions: AGENT_PERMISSIONS["A03"] ?? [], approvalRequired: false },
  { id: "A04", name: "Narrative Director", domain: "design", capabilities: AGENT_CAPABILITIES["A04"] ?? [], permissions: AGENT_PERMISSIONS["A04"] ?? [], approvalRequired: false },
  { id: "A05", name: "Story Architect", domain: "design", capabilities: AGENT_CAPABILITIES["A05"] ?? [], permissions: AGENT_PERMISSIONS["A05"] ?? [], approvalRequired: false },
  { id: "A06", name: "Character Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A06"] ?? [], permissions: AGENT_PERMISSIONS["A06"] ?? [], approvalRequired: false },
  { id: "A07", name: "World Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A07"] ?? [], permissions: AGENT_PERMISSIONS["A07"] ?? [], approvalRequired: false },
  { id: "A08", name: "Level Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A08"] ?? [], permissions: AGENT_PERMISSIONS["A08"] ?? [], approvalRequired: false },
  { id: "A09", name: "Quest Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A09"] ?? [], permissions: AGENT_PERMISSIONS["A09"] ?? [], approvalRequired: false },
  { id: "A10", name: "Dialogue Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A10"] ?? [], permissions: AGENT_PERMISSIONS["A10"] ?? [], approvalRequired: false },
  { id: "A11", name: "Cinematic Director", domain: "design", capabilities: AGENT_CAPABILITIES["A11"] ?? [], permissions: AGENT_PERMISSIONS["A11"] ?? [], approvalRequired: false },
  { id: "A12", name: "Camera Director", domain: "design", capabilities: AGENT_CAPABILITIES["A12"] ?? [], permissions: AGENT_PERMISSIONS["A12"] ?? [], approvalRequired: false },
  { id: "A13", name: "Gameplay Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A13"] ?? [], permissions: AGENT_PERMISSIONS["A13"] ?? [], approvalRequired: false },
  { id: "A14", name: "Systems Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A14"] ?? [], permissions: AGENT_PERMISSIONS["A14"] ?? [], approvalRequired: false },
  { id: "A15", name: "Economy Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A15"] ?? [], permissions: AGENT_PERMISSIONS["A15"] ?? [], approvalRequired: false },
  { id: "A16", name: "UX/UI Designer", domain: "design", capabilities: AGENT_CAPABILITIES["A16"] ?? [], permissions: AGENT_PERMISSIONS["A16"] ?? [], approvalRequired: false },
  { id: "A17", name: "Technical Director", domain: "design", capabilities: AGENT_CAPABILITIES["A17"] ?? [], permissions: AGENT_PERMISSIONS["A17"] ?? [], approvalRequired: false },
  { id: "A18", name: "Engine Specialist", domain: "design", capabilities: AGENT_CAPABILITIES["A18"] ?? [], permissions: AGENT_PERMISSIONS["A18"] ?? [], approvalRequired: false },
  { id: "A19", name: "Code Architect", domain: "design", capabilities: AGENT_CAPABILITIES["A19"] ?? [], permissions: AGENT_PERMISSIONS["A19"] ?? [], approvalRequired: false },
  { id: "A20", name: "Code Generator", domain: "design", capabilities: AGENT_CAPABILITIES["A20"] ?? [], permissions: AGENT_PERMISSIONS["A20"] ?? [], approvalRequired: false },
  { id: "A21", name: "AI/ML Specialist", domain: "design", capabilities: AGENT_CAPABILITIES["A21"] ?? [], permissions: AGENT_PERMISSIONS["A21"] ?? [], approvalRequired: false },
  { id: "A22", name: "Asset Director", domain: "production", capabilities: AGENT_CAPABILITIES["A22"] ?? [], permissions: AGENT_PERMISSIONS["A22"] ?? [], approvalRequired: false },
  { id: "A23", name: "2D Artist", domain: "production", capabilities: AGENT_CAPABILITIES["A23"] ?? [], permissions: AGENT_PERMISSIONS["A23"] ?? [], approvalRequired: false },
  { id: "A24", name: "3D Artist", domain: "production", capabilities: AGENT_CAPABILITIES["A24"] ?? [], permissions: AGENT_PERMISSIONS["A24"] ?? [], approvalRequired: false },
  { id: "A25", name: "Texture & Material Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A25"] ?? [], permissions: AGENT_PERMISSIONS["A25"] ?? [], approvalRequired: false },
  { id: "A26", name: "Animation Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A26"] ?? [], permissions: AGENT_PERMISSIONS["A26"] ?? [], approvalRequired: false },
  { id: "A27", name: "Rigging Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A27"] ?? [], permissions: AGENT_PERMISSIONS["A27"] ?? [], approvalRequired: false },
  { id: "A28", name: "VFX Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A28"] ?? [], permissions: AGENT_PERMISSIONS["A28"] ?? [], approvalRequired: false },
  { id: "A29", name: "Audio Director", domain: "production", capabilities: AGENT_CAPABILITIES["A29"] ?? [], permissions: AGENT_PERMISSIONS["A29"] ?? [], approvalRequired: false },
  { id: "A30", name: "Music Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A30"] ?? [], permissions: AGENT_PERMISSIONS["A30"] ?? [], approvalRequired: false },
  { id: "A31", name: "SFX Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A31"] ?? [], permissions: AGENT_PERMISSIONS["A31"] ?? [], approvalRequired: false },
  { id: "A32", name: "Voice/Dubbing Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A32"] ?? [], permissions: AGENT_PERMISSIONS["A32"] ?? [], approvalRequired: false },
  { id: "A33", name: "Localization Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A33"] ?? [], permissions: AGENT_PERMISSIONS["A33"] ?? [], approvalRequired: false },
  { id: "A34", name: "Optimization Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A34"] ?? [], permissions: AGENT_PERMISSIONS["A34"] ?? [], approvalRequired: false },
  { id: "A35", name: "QA Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A35"] ?? [], permissions: AGENT_PERMISSIONS["A35"] ?? [], approvalRequired: false },
  { id: "A36", name: "Playtest Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A36"] ?? [], permissions: AGENT_PERMISSIONS["A36"] ?? [], approvalRequired: false },
  { id: "A37", name: "Security Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A37"] ?? [], permissions: AGENT_PERMISSIONS["A37"] ?? [], approvalRequired: false },
  { id: "A38", name: "IP/License Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A38"] ?? [], permissions: AGENT_PERMISSIONS["A38"] ?? [], approvalRequired: false },
  { id: "A39", name: "Build Agent", domain: "production", capabilities: AGENT_CAPABILITIES["A39"] ?? [], permissions: AGENT_PERMISSIONS["A39"] ?? [], approvalRequired: true },
  { id: "A40", name: "Release Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A40"] ?? [], permissions: AGENT_PERMISSIONS["A40"] ?? [], approvalRequired: true },
  { id: "A41", name: "GitHub Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A41"] ?? [], permissions: AGENT_PERMISSIONS["A41"] ?? [], approvalRequired: false },
  { id: "A42", name: "Cloud Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A42"] ?? [], permissions: AGENT_PERMISSIONS["A42"] ?? [], approvalRequired: false },
  { id: "A43", name: "Documentation Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A43"] ?? [], permissions: AGENT_PERMISSIONS["A43"] ?? [], approvalRequired: false },
  { id: "A44", name: "Continuity Doctor", domain: "platform", capabilities: AGENT_CAPABILITIES["A44"] ?? [], permissions: AGENT_PERMISSIONS["A44"] ?? [], approvalRequired: false },
  { id: "A45", name: "Narrative QA", domain: "platform", capabilities: AGENT_CAPABILITIES["A45"] ?? [], permissions: AGENT_PERMISSIONS["A45"] ?? [], approvalRequired: false },
  { id: "A46", name: "Game Balance Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A46"] ?? [], permissions: AGENT_PERMISSIONS["A46"] ?? [], approvalRequired: false },
  { id: "A47", name: "Mobile Optimization Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A47"] ?? [], permissions: AGENT_PERMISSIONS["A47"] ?? [], approvalRequired: false },
  { id: "A48", name: "Performance Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A48"] ?? [], permissions: AGENT_PERMISSIONS["A48"] ?? [], approvalRequired: false },
  { id: "A49", name: "Provider Router Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A49"] ?? [], permissions: AGENT_PERMISSIONS["A49"] ?? [], approvalRequired: false },
  { id: "A50", name: "Model Registry Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A50"] ?? [], permissions: AGENT_PERMISSIONS["A50"] ?? [], approvalRequired: false },
  { id: "A51", name: "Game Knowledge Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A51"] ?? [], permissions: AGENT_PERMISSIONS["A51"] ?? [], approvalRequired: false },
  { id: "A52", name: "Research Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A52"] ?? [], permissions: AGENT_PERMISSIONS["A52"] ?? [], approvalRequired: false },
  { id: "A53", name: "Ideation Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A53"] ?? [], permissions: AGENT_PERMISSIONS["A53"] ?? [], approvalRequired: false },
  { id: "A54", name: "GDD Compiler", domain: "platform", capabilities: AGENT_CAPABILITIES["A54"] ?? [], permissions: AGENT_PERMISSIONS["A54"] ?? [], approvalRequired: false },
  { id: "A55", name: "Game Compiler", domain: "platform", capabilities: AGENT_CAPABILITIES["A55"] ?? [], permissions: AGENT_PERMISSIONS["A55"] ?? [], approvalRequired: false },
  { id: "A56", name: "World Simulation Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A56"] ?? [], permissions: AGENT_PERMISSIONS["A56"] ?? [], approvalRequired: false },
  { id: "A57", name: "NPC Intelligence Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A57"] ?? [], permissions: AGENT_PERMISSIONS["A57"] ?? [], approvalRequired: false },
  { id: "A58", name: "Multiplayer Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A58"] ?? [], permissions: AGENT_PERMISSIONS["A58"] ?? [], approvalRequired: false },
  { id: "A59", name: "Monetization Systems Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A59"] ?? [], permissions: AGENT_PERMISSIONS["A59"] ?? [], approvalRequired: false },
  { id: "A60", name: "Store Publishing Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A60"] ?? [], permissions: AGENT_PERMISSIONS["A60"] ?? [], approvalRequired: true },
  { id: "A61", name: "Telemetry Agent", domain: "platform", capabilities: AGENT_CAPABILITIES["A61"] ?? [], permissions: AGENT_PERMISSIONS["A61"] ?? [], approvalRequired: false }
];
