import type { EngineId } from "./contracts";

export interface EngineProjectInput {
  engine: EngineId;
  projectId: string;
  name: string;
  packageName?: string;
  generatedAt?: string;
}

export interface EngineProjectFile {
  path: string;
  content: string;
}

const safe = (value: string) => value.trim().replace(/[^a-zA-Z0-9_-]+/g, "_").replace(/^_+|_+$/g, "") || "game";
const json = (value: unknown) => JSON.stringify(value, null, 2) + "\n";

function commonManifest(input: EngineProjectInput) {
  return {
    factory: "AI GAME FACTORY",
    schemaVersion: "1.0",
    engine: input.engine,
    projectId: input.projectId,
    name: input.name,
    generatedAt: input.generatedAt ?? new Date().toISOString(),
  };
}

export function generateEngineProjectFiles(input: EngineProjectInput): EngineProjectFile[] {
  if (!input.projectId.trim()) throw new Error("projectId is required.");
  if (!input.name.trim()) throw new Error("name is required.");
  const name = input.name.trim();
  const id = safe(input.packageName || input.projectId).toLowerCase();
  const manifest = { path: "factory/project-manifest.json", content: json(commonManifest(input)) };

  switch (input.engine) {
    case "unreal":
      return [
        manifest,
        { path: id + ".uproject", content: json({ FileVersion: 3, EngineAssociation: "5.0", Modules: [{ Name: id, Type: "Runtime", LoadingPhase: "Default" }], Plugins: [] }) },
        { path: "Source/" + id + "/" + id + ".Build.cs", content: "using UnrealBuildTool;\n\npublic class " + id + " : ModuleRules\n{\n    public " + id + "(ReadOnlyTargetRules Target) : base(Target) { PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs; }\n}\n" },
        { path: "Source/" + id + "Editor.Target.cs", content: "using UnrealBuildTool;\n\npublic class " + id + "EditorTarget : TargetRules\n{\n    public " + id + "EditorTarget(TargetInfo Target) : base(Target) { Type = TargetType.Editor; ExtraModuleNames.Add(\"" + id + "\"); }\n}\n" },
        { path: "Source/" + id + ".Target.cs", content: "using UnrealBuildTool;\n\npublic class " + id + "Target : TargetRules\n{\n    public " + id + "Target(TargetInfo Target) : base(Target) { Type = TargetType.Game; ExtraModuleNames.Add(\"" + id + "\"); }\n}\n" },
      ];
    case "unity":
      return [
        manifest,
        { path: "ProjectSettings/ProjectVersion.txt", content: "m_EditorVersion: 6000.0.0f1\nm_EditorVersionWithRevision: 6000.0.0f1 (factory)\n" },
        { path: "ProjectSettings/ProjectSettings.asset", content: "%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n--- !u!129 &1\nPlayerSettings:\n  productGUID: " + input.projectId.slice(0, 32).padEnd(32, "0") + "\n  productName: " + name + "\n" },
        { path: "Assets/Scenes/Main.unity", content: "%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n--- !u!1045 &1\nEditorBuildSettings:\n  m_Scenes: []\n" },
        { path: "Assets/Scripts/FactoryBootstrap.cs", content: "using UnityEngine;\n\npublic sealed class FactoryBootstrap : MonoBehaviour { }\n" },
        { path: "Assets/Scripts/FactoryBuild.cs", content: "using UnityEditor;\nusing UnityEditor.Build.Reporting;\n\npublic static class FactoryBuild {\n    public static void Build() {\n        var output = \"build/game\";\n        BuildPipeline.BuildPlayer(EditorBuildSettings.scenes, output, EditorUserBuildSettings.activeBuildTarget, BuildOptions.None);\n    }\n}\n" },
        { path: "Packages/manifest.json", content: json({ dependencies: { "com.unity.modules.ai": "1.0.0", "com.unity.modules.physics": "1.0.0", "com.unity.modules.ui": "1.0.0" } }) },
      ];
    case "godot":
      return [
        manifest,
        { path: "project.godot", content: "[application]\nconfig/name=\"" + name.replace(/"/g, "\\\"") + "\"\nrun/main_scene=\"res://scenes/main.tscn\"\n[display]\nwindow/size/viewport_width=1920\nwindow/size/viewport_height=1080\n[rendering]\nrenderer/rendering_method=\"gl_compatibility\"\n" },
        { path: "scenes/main.tscn", content: "[gd_scene load_steps=2 format=3]\n\n[ext_resource path=\"res://scripts/main.gd\" type=\"Script\" id=\"1\"]\n\n[node name=\"Main\" type=\"Node\"]\nscript = ExtResource(\"1\")\n" },
        { path: "export_presets.cfg", content: '[preset.0]\nname="Linux/X11"\nplatform="Linux/X11"\n[preset.0.options]\n\n[preset.1]\nname="Android"\nplatform="Android"\n[preset.1.options]\n\n[preset.2]\nname="Web"\nplatform="Web"\n[preset.2.options]\n\n' },
        { path: "scripts/main.gd", content: "extends Node\n\nfunc _ready() -> void:\n    print(\"" + name.replace(/"/g, "\\\"") + " generated by AI GAME FACTORY\")\n" },
      ];
    case "cocos":
      return [
        manifest,
        { path: "package.json", content: json({ name: id, version: "0.1.0", description: name, private: true }) },
        { path: "settings/v2/packages.json", content: json({}) },
        { path: "assets/main.ts", content: "export const FACTORY_PROJECT = " + JSON.stringify(input.projectId) + ";\n" },
      ];
    case "defold":
      return [
        manifest,
        { path: "game.project", content: "[project]\ntitle = " + JSON.stringify(name) + "\nversion = 0.1.0\n[display]\nwidth = 960\nheight = 540\n[bootstrap]\nmain_collection = /main/main.collectionc\n" },
        { path: "main/main.collection", content: "components {\n  id: \"factory\"\n  component: \"/main/factory.script\"\n}\n" },
        { path: "main/factory.script", content: "function init(self)\n    print(\"" + name.replace(/"/g, "\\\"") + " generated by AI GAME FACTORY\")\nend\n" },
      ];
    case "stride":
      return [
        manifest,
        { path: id + ".csproj", content: "<Project Sdk=\"Microsoft.NET.Sdk\">\n  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><RootNamespace>" + id + "</RootNamespace></PropertyGroup>\n</Project>\n" },
        { path: "Game/GameBootstrap.cs", content: "namespace " + id + ";\npublic static class GameBootstrap { public static void Main() { } }\n" },
      ];
    case "monogame":
      return [
        manifest,
        { path: id + ".csproj", content: "<Project Sdk=\"Microsoft.NET.Sdk\">\n  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable></PropertyGroup>\n  <ItemGroup><PackageReference Include=\"MonoGame.Framework.DesktopGL\" Version=\"3.8.2.1105\" /></ItemGroup>\n</Project>\n" },
        { path: "Program.cs", content: "using System;\npublic static class Program { public static void Main() => Console.WriteLine(\"" + name.replace(/"/g, "\\\"") + " generated by AI GAME FACTORY\"); }\n" },
      ];
    case "bevy":
      return [
        manifest,
        { path: "Cargo.toml", content: "[package]\nname = \"" + id.toLowerCase() + "\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nbevy = \"0.15\"\n" },
        { path: "src/main.rs", content: "use bevy::prelude::*;\n\nfn main() { App::new().add_plugins(DefaultPlugins).add_systems(Startup, setup).run(); }\nfn setup() { info!(\"" + name.replace(/"/g, "\\\"") + " generated by AI GAME FACTORY\"); }\n" },
      ];
    case "o3de":
      return [
        manifest,
        { path: "project.json", content: json({ project_name: name, engine: "o3de", origin: "AI GAME FACTORY" }) },
        { path: "Registry/ai-game-factory.setreg", content: "{}\n" },
        { path: "Code/CMakeLists.txt", content: "cmake_minimum_required(VERSION 3.30)\nproject(" + id + ")\n" },
      ];
    case "html5":
      return [
        manifest,
        { path: "index.html", content: "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>" + name.replace(/</g, "&lt;") + "</title></head><body><canvas id=\"game\"></canvas><script type=\"module\" src=\"./src/main.js\"></script></body></html>\n" },
        { path: "src/main.js", content: "const canvas = document.querySelector('#game');\ncanvas.width = innerWidth; canvas.height = innerHeight;\nconsole.info(" + JSON.stringify(name + " generated by AI GAME FACTORY") + ");\n" },
        { path: "package.json", content: json({ name: id, version: "0.1.0", private: true, scripts: { build: "echo static-web-build" } }) },
      ];
    case "renpy":
      return [
        manifest,
        { path: "game/script.rpy", content: 'label start:\n    "' + name.replace(/"/g, "'") + ' — generated by AI GAME FACTORY."\n    return\n' },
        { path: "game/options.rpy", content: "define config.name = " + JSON.stringify(name) + "\ndefine config.version = \"0.1.0\"\n" },
      ];
    case "custom":
      return [
        manifest,
        { path: "runtime.manifest.json", content: json({ schemaVersion: "1.0", projectId: input.projectId, name, entrypoint: "src/main.ts", build: "build" }) },
        { path: "src/main.ts", content: "export function main() { return " + JSON.stringify({ projectId: input.projectId, name }) + "; }\n" },
        { path: "README.md", content: "# " + name + "\n\nGenerated by AI GAME FACTORY Custom Runtime adapter.\n" },
      ];
  }
}

export function validateGeneratedProjectFiles(engine: EngineId, files: EngineProjectFile[]): string[] {
  const required: Record<EngineId, string[]> = {
    unreal: [".uproject"], unity: ["ProjectSettings/ProjectVersion.txt"], godot: ["project.godot", "scenes/main.tscn"],
    cocos: ["package.json"], defold: ["game.project"], stride: [".csproj"], monogame: [".csproj", "Program.cs"],
    bevy: ["Cargo.toml", "src/main.rs"], o3de: ["project.json"], html5: ["index.html", "src/main.js"],
    renpy: ["game/script.rpy", "game/options.rpy"], custom: ["runtime.manifest.json"],
  };
  const paths = files.map(f => f.path);
  return (required[engine] || []).filter(requiredPath => {
    if (requiredPath === ".uproject" || requiredPath === ".csproj") return paths.some(p => p.endsWith(requiredPath));
    return !paths.includes(requiredPath);
  }).map(path => engine + " project missing required file: " + path);
}
