export const UNITY_ENGINE_OPERATIONS = ["read_project_context","inspect_scene","inspect_game_object","inspect_components","inspect_packages","inspect_scripts","inspect_prefabs","inspect_materials","inspect_animations","inspect_terrain","assistant","code_agent","scene_agent","asset_generator","mcp_action","ai_gateway_action","sentis_runtime_model","build"] as const;

import type { EngineAdapter, EngineCapability, EngineOperation, EngineResult } from "./engine-adapter";
export type UnityAssistantMode = "ask" | "plan" | "agent" | "run" | "code";
export interface UnityProjectContext { projectId:string; unityVersion:string; cloudProjectId?:string; targetPlatform?:string; scenePath?:string; sceneGraph?:string[]; gameObjects?:string[]; components?:string[]; packages?:string[]; scripts?:string[]; prefabs?:string[]; materials?:string[]; animations?:string[]; terrain?:string[]; settings?:Record<string,unknown>; serializedInspector?:Record<string,unknown>; }
export interface UnityMCPBridgeConfig { enabled:boolean; endpoint?:string; transport?:"stdio"|"http"|"sse"; projectContext:boolean; allowEditorActions:boolean; allowReadLogs:boolean; }
export interface UnityAIGatewayConfig { enabled:boolean; provider?:string; model?:string; secretRef?:string; audit?:boolean; }
export interface UnityRuntimeMLConfig { enabled:boolean; runtime:"sentis"; modelUris?:string[]; }
export interface UnityEngineAdapterConfig { projectPath?:string; unityVersion?:string; cloudProjectId?:string; mcp?:UnityMCPBridgeConfig; aiGateway?:UnityAIGatewayConfig; runtimeML?:UnityRuntimeMLConfig; }
export interface UnityProjectContextProvider { read(projectId:string):Promise<UnityProjectContext>; }
export interface UnityEditorBridge { execute(input:{projectId:string;action:string;payload:Record<string,unknown>;context:UnityProjectContext}):Promise<{status:"queued"|"running"|"succeeded"|"failed";jobId?:string;artifacts?:string[];diagnostics?:string[]}>; }
export const UNITY_ENGINE_CAPABILITIES:readonly EngineCapability[]=["project_bootstrap","scene_edit","code_edit","asset_import","animation","physics","ui","navigation","save_system","test","build"];
function assertUnity6OrLater(version:string):void { const match=version.match(/(?:Unity\\s*)?(\\d+)\\.(\\d+)/i); if(!match)return; if(Number(match[1])<6)throw new Error("UNITY_AI_REQUIRES_UNITY_6_OR_NEWER"); }
export class UnityEngineAdapter implements EngineAdapter { readonly id="unity" as const; readonly name="Unity Engine Adapter"; readonly version:string; readonly capabilities:EngineCapability[]=[...UNITY_ENGINE_CAPABILITIES]; constructor(private readonly config:UnityEngineAdapterConfig={},private readonly contextProvider?:UnityProjectContextProvider,private readonly bridge?:UnityEditorBridge){this.version=config.unityVersion??"6+";if(config.unityVersion)assertUnity6OrLater(config.unityVersion);} async bootstrap(input:Record<string,unknown>):Promise<EngineResult>{const projectId=String(input.projectId??"");if(!projectId)return{status:"failed",diagnostics:["Unity bootstrap requires projectId."]};return{status:"queued",jobId:"unity:bootstrap:"+projectId,diagnostics:["Unity project bootstrap delegated to the Unity worker/editor.","The Factory does not emulate or bundle the Unity Editor."]};} async execute(operation:EngineOperation):Promise<EngineResult>{if(!operation.projectId.trim())return{status:"failed",diagnostics:["Unity operation requires projectId."]};if(operation.capability==="build")return this.build(String(operation.payload.target??""));if(!this.bridge)return{status:"queued",jobId:"unity:operation:"+operation.projectId,diagnostics:["Unity operation is ready for an attached Unity Editor worker.","No live Unity bridge is configured in this process."]};const context=this.contextProvider?await this.contextProvider.read(operation.projectId):{projectId:operation.projectId,unityVersion:this.version};return this.bridge.execute({projectId:operation.projectId,action:String(operation.payload.action??operation.capability),payload:operation.payload,context});} async build(target:string):Promise<EngineResult>{if(!target.trim())return{status:"failed",diagnostics:["Unity build target is required."]};return{status:"queued",jobId:"unity:build:"+target,diagnostics:["Unity Build Adapter queued the target.","Actual build execution requires a Unity project worker/editor and installed Unity version."]};} async readContext(projectId:string):Promise<UnityProjectContext>{return this.contextProvider?this.contextProvider.read(projectId):{projectId,unityVersion:this.version};} async runAssistant(projectId:string,prompt:string,mode:UnityAssistantMode="ask"):Promise<EngineResult>{if(!prompt.trim())return{status:"failed",diagnostics:["Assistant prompt is required."]};return this.execute({projectId,capability:"code_edit",payload:{action:"assistant",mode,prompt}});} mcpAvailable():boolean{return this.config.mcp?.enabled===true;} aiGatewayAvailable():boolean{return this.config.aiGateway?.enabled===true;} runtimeMLAvailable():boolean{return this.config.runtimeML?.enabled===true;} }
